# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ResultWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ResultWidget(object):
    def setupUi(self, ResultWidget):
        ResultWidget.setObjectName("ResultWidget")
        ResultWidget.resize(683, 244)
        self.ResultLabel = QtWidgets.QLabel(ResultWidget)
        self.ResultLabel.setGeometry(QtCore.QRect(20, 30, 631, 191))
        self.ResultLabel.setObjectName("ResultLabel")

        self.retranslateUi(ResultWidget)
        QtCore.QMetaObject.connectSlotsByName(ResultWidget)

    def retranslateUi(self, ResultWidget):
        _translate = QtCore.QCoreApplication.translate
        ResultWidget.setWindowTitle(_translate("ResultWidget", "翻译结果"))
        self.ResultLabel.setText(_translate("ResultWidget", "无"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ResultWidget = QtWidgets.QWidget()
    ui = Ui_ResultWidget()
    ui.setupUi(ResultWidget)
    ResultWidget.show()
    sys.exit(app.exec_())
