# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(712, 274)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 111, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 20, 261, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 151, 41))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(160, 70, 91, 41))
        self.label_4.setObjectName("label_4")
        self.leftUpXEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.leftUpXEdit.setGeometry(QtCore.QRect(260, 80, 91, 21))
        self.leftUpXEdit.setObjectName("leftUpXEdit")
        self.leftUpYEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.leftUpYEdit.setGeometry(QtCore.QRect(470, 80, 91, 21))
        self.leftUpYEdit.setObjectName("leftUpYEdit")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(370, 70, 91, 41))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(370, 120, 91, 41))
        self.label_6.setObjectName("label_6")
        self.rightDownXEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.rightDownXEdit.setGeometry(QtCore.QRect(260, 130, 91, 21))
        self.rightDownXEdit.setObjectName("rightDownXEdit")
        self.rightDownXEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.rightDownXEdit_2.setGeometry(QtCore.QRect(470, 130, 91, 21))
        self.rightDownXEdit_2.setObjectName("rightDownXEdit_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(160, 120, 91, 41))
        self.label_7.setObjectName("label_7")
        self.beginTranslateButton = QtWidgets.QPushButton(self.centralwidget)
        self.beginTranslateButton.setGeometry(QtCore.QRect(20, 180, 111, 31))
        self.beginTranslateButton.setObjectName("beginTranslateButton")
        self.stopTranslateButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopTranslateButton.setGeometry(QtCore.QRect(160, 180, 111, 31))
        self.stopTranslateButton.setObjectName("stopTranslateButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 712, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OCR翻译器"))
        self.label.setText(_translate("MainWindow", "当前鼠标位置："))
        self.label_2.setText(_translate("MainWindow", "X坐标：100；Y坐标：100"))
        self.label_3.setText(_translate("MainWindow", "输入截取屏幕区域："))
        self.label_4.setText(_translate("MainWindow", "左上X坐标："))
        self.label_5.setText(_translate("MainWindow", "左上Y坐标："))
        self.label_6.setText(_translate("MainWindow", "右下Y坐标："))
        self.label_7.setText(_translate("MainWindow", "右下X坐标："))
        self.beginTranslateButton.setText(_translate("MainWindow", "开始翻译"))
        self.stopTranslateButton.setText(_translate("MainWindow", "停止翻译"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
